blank_issues_enabled: true
contact_links:
  - name: Questions and Answers
    url: https://github.com/seqan/sharg-parser/discussions
    about: Ask us about installing and using Sharg in our discussions forum!
